use std::{
    fs,
    path::{Path, PathBuf},
    process::{Command, Output, Stdio},
    sync::atomic::{AtomicU64, Ordering},
    time::Duration,
};

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

static NEXT_TEMP_DIR: AtomicU64 = AtomicU64::new(0);

struct TempDir(PathBuf);

impl TempDir {
    fn new(name: &str) -> Self {
        loop {
            let sequence = NEXT_TEMP_DIR.fetch_add(1, Ordering::Relaxed);
            let path =
                std::env::temp_dir().join(format!("ink-{name}-{}-{sequence}", std::process::id()));
            match fs::create_dir(&path) {
                Ok(()) => return Self(path),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
                Err(error) => panic!("temporary directory should be created: {error}"),
            }
        }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn ink(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_ink"))
        .args(args)
        .stdin(Stdio::null())
        .output()
        .expect("ink command should run")
}

fn executable(path: &Path, contents: &str) {
    fs::write(path, contents).expect("test executable should be written");
    let mut permissions = fs::metadata(path)
        .expect("test executable metadata should be available")
        .permissions();
    permissions.set_mode(0o755);
    fs::set_permissions(path, permissions).expect("test executable should be executable");
}

#[test]
fn comp_001_generate_common_shell_completions() {
    for shell in ["bash", "zsh", "fish"] {
        let output = ink(&["completion", shell]);
        assert!(output.status.success());
        let script = String::from_utf8_lossy(&output.stdout);
        assert!(script.contains("@generated by usage-argv"));
        assert!(script.contains("ink __complete_word__"));
    }
}
#[test]
fn comp_002_generate_a_portable_shell_completion() {
    let output = ink(&["completion", "nu"]);
    assert!(output.status.success());
    let script = String::from_utf8_lossy(&output.stdout);
    assert!(script.contains("def --env"));
    assert!(script.contains("^ink __complete_word__"));
}
#[test]
fn comp_003_completion_generation_has_no_prompt_side_effects() {
    for shell in ["bash", "zsh", "fish", "nu"] {
        let output = ink(&["completion", shell]);
        assert!(output.status.success(), "failed to generate {shell}");
        assert!(output.stderr.is_empty(), "unexpected stderr for {shell}");
        assert!(
            !output.stdout.contains(&b'\x1b'),
            "terminal control byte in {shell} completion"
        );
    }
}

#[test]
fn perf_001_normal_startup_uses_compiled_tables() {
    let temp = TempDir::new("compiled-cli");
    let usage = temp.0.join("usage");
    let marker = temp.0.join("usage-was-spawned");
    executable(
        &usage,
        "#!/bin/sh\nprintf invoked > \"$INK_USAGE_MARKER\"\nexit 99\n",
    );

    for subcommand in ["input", "textarea"] {
        Command::new(env!("CARGO_BIN_EXE_ink"))
            .arg(subcommand)
            .current_dir(&temp.0)
            .env("PATH", &temp.0)
            .env("INK_USAGE_MARKER", &marker)
            .stdin(Stdio::null())
            .output()
            .expect("ink should parse without an external usage executable");
        assert!(!marker.exists(), "normal parsing spawned external usage");
    }
}

#[test]
fn perf_002_startup_benchmark_uses_stable_sampling() {
    let mut invocations = 0;
    let median = ink::startup_bench::measure(|| {
        invocations += 1;
        Duration::from_millis(invocations)
    });
    assert_eq!(invocations, 120);
    assert_eq!(
        median,
        Duration::from_millis(70) + Duration::from_micros(500)
    );

    let output = Command::new(env!("CARGO_BIN_EXE_startup-bench"))
        .arg(env!("CARGO_BIN_EXE_ink"))
        .env_remove("INK_ENFORCE_STARTUP_BUDGET")
        .output()
        .expect("startup benchmark should run");
    assert!(output.status.success());
    let report = String::from_utf8_lossy(&output.stdout);
    assert!(report.contains("ink --version median:"));
    assert!(report.contains("(20 warmups, 100 samples)"));
}

#[test]
fn perf_003_startup_stays_within_budget() {
    let budget = Duration::from_millis(20);
    assert!(!ink::startup_bench::budget_exceeded(
        false,
        budget + Duration::from_secs(1)
    ));
    assert!(!ink::startup_bench::budget_exceeded(true, budget));
    assert!(ink::startup_bench::budget_exceeded(
        true,
        budget + Duration::from_nanos(1)
    ));
}
