#[test]
fn comp_001_generate_common_shell_completions() {
    for shell in ["bash", "zsh", "fish"] {
        let output = std::process::Command::new(env!("CARGO_BIN_EXE_ink"))
            .args(["completion", shell])
            .output()
            .expect("completion command should run");
        assert!(output.status.success());
        let script = String::from_utf8_lossy(&output.stdout);
        assert!(script.contains("@generated by usage-argv"));
        assert!(script.contains("ink __complete_word__"));
    }
}
#[test]
fn comp_002_generate_a_portable_shell_completion() {
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_ink"))
        .args(["completion", "nu"])
        .output()
        .expect("completion command should run");
    assert!(output.status.success());
    assert!(String::from_utf8_lossy(&output.stdout).contains("def --env"));
}
#[test]
fn comp_003_completion_generation_has_no_prompt_side_effects() {
    let output = std::process::Command::new(env!("CARGO_BIN_EXE_ink"))
        .args(["completion", "bash"])
        .stdin(std::process::Stdio::null())
        .output()
        .expect("completion command should run");
    assert!(output.status.success());
    assert!(output.stderr.is_empty());
    assert!(!output.stdout.contains(&b'\x1b'));
}
#[test]
#[ignore = "bootstrap: product behavior not implemented"]
fn perf_001_normal_startup_uses_compiled_tables() {
    deferred!()
}
#[test]
#[ignore = "bootstrap: product behavior not implemented"]
fn perf_002_startup_benchmark_uses_stable_sampling() {
    deferred!()
}
#[test]
#[ignore = "bootstrap: product behavior not implemented"]
fn perf_003_startup_stays_within_budget() {
    deferred!()
}
