use std::{
    ffi::OsStr,
    fs,
    io::Read,
    path::PathBuf,
    process::{Command, ExitCode, Output, Stdio},
    sync::atomic::{AtomicU64, Ordering},
    thread,
    time::{Duration, Instant},
};

use ink::cli::{CliRuntime, PromptKind};
use ink::startup_bench::{ENFORCE_BUDGET_ENV, SAMPLE_FIXTURE_ENV, SAMPLES, WARMUPS};

static NEXT_TEMP_DIR: AtomicU64 = AtomicU64::new(0);

struct TempDir(PathBuf);

impl TempDir {
    fn new(name: &str) -> Self {
        loop {
            let sequence = NEXT_TEMP_DIR.fetch_add(1, Ordering::Relaxed);
            let path =
                std::env::temp_dir().join(format!("ink-{name}-{}-{sequence}", std::process::id()));
            match fs::create_dir(&path) {
                Ok(()) => return Self(path),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
                Err(error) => panic!("temporary directory should be created: {error}"),
            }
        }
    }
}

impl Drop for TempDir {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn ink(args: &[&str]) -> Output {
    ink_command(args)
        .stdin(Stdio::null())
        .output()
        .expect("ink command should run")
}

fn ink_command(args: &[&str]) -> Command {
    let mut command = Command::new(env!("CARGO_BIN_EXE_ink"));
    command.args(args);
    command
}

fn ink_with_open_stdin(args: &[&str]) -> Output {
    let mut child = ink_command(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("ink command should start");
    let mut stdout = child.stdout.take().expect("ink stdout should be piped");
    let mut stderr = child.stderr.take().expect("ink stderr should be piped");
    let stdout_reader = thread::spawn(move || {
        let mut output = Vec::new();
        stdout
            .read_to_end(&mut output)
            .expect("ink stdout should be read");
        output
    });
    let stderr_reader = thread::spawn(move || {
        let mut output = Vec::new();
        stderr
            .read_to_end(&mut output)
            .expect("ink stderr should be read");
        output
    });
    let deadline = Instant::now() + Duration::from_secs(2);
    let status = loop {
        if let Some(status) = child.try_wait().expect("ink status should be available") {
            break status;
        }
        if Instant::now() >= deadline {
            child.kill().expect("blocked ink command should be killed");
            child.wait().expect("killed ink command should be reaped");
            panic!("ink blocked while generating completion with open stdin");
        }
        thread::sleep(Duration::from_millis(10));
    };
    Output {
        status,
        stdout: stdout_reader.join().expect("stdout reader should finish"),
        stderr: stderr_reader.join().expect("stderr reader should finish"),
    }
}

#[derive(Default)]
struct RuntimeProbe {
    stdout: String,
    prompts: Vec<PromptKind>,
    stdin_reads: usize,
    terminal_opens: usize,
}

impl CliRuntime for RuntimeProbe {
    fn write_stdout(&mut self, text: &str) {
        self.stdout.push_str(text);
    }

    fn read_stdin(&mut self) {
        self.stdin_reads += 1;
    }

    fn open_controlling_terminal(&mut self) {
        self.terminal_opens += 1;
    }

    fn run_prompt(&mut self, kind: PromptKind) -> ExitCode {
        self.prompts.push(kind);
        ExitCode::SUCCESS
    }
}

#[test]
fn comp_001_generate_common_shell_completions() {
    for shell in ["bash", "zsh", "fish"] {
        let output = ink(&["completion", shell]);
        assert!(output.status.success());
        let script = String::from_utf8_lossy(&output.stdout);
        assert!(script.contains("@generated by usage-argv"));
        assert!(script.contains("ink __complete_word__"));
    }
}
#[test]
fn comp_002_generate_a_portable_shell_completion() {
    let output = ink(&["completion", "nu"]);
    assert!(output.status.success());
    let script = String::from_utf8_lossy(&output.stdout);
    assert!(script.contains("def --env"));
    assert!(script.contains("^ink __complete_word__"));
}
#[test]
fn comp_003_completion_generation_has_no_prompt_side_effects() {
    for shell in ["bash", "zsh", "fish", "nu"] {
        let output = ink_with_open_stdin(&["completion", shell]);
        assert!(output.status.success(), "failed to generate {shell}");
        assert!(output.stderr.is_empty(), "unexpected stderr for {shell}");
        assert!(
            !output.stdout.contains(&b'\x1b'),
            "terminal control byte in {shell} completion"
        );

        let mut runtime = RuntimeProbe::default();
        let args = [OsStr::new("completion"), OsStr::new(shell)];
        let status = ink::cli::run_from(&args, &mut runtime).expect("completion should parse");
        assert_eq!(status, std::process::ExitCode::SUCCESS);
        assert!(runtime.prompts.is_empty(), "completion entered prompt I/O");
        assert_eq!(runtime.stdin_reads, 0, "completion read stdin");
        assert_eq!(runtime.terminal_opens, 0, "completion opened a terminal");
        assert_eq!(runtime.stdout.as_bytes(), output.stdout);
    }
}

#[test]
fn perf_001_normal_startup_uses_compiled_tables() {
    for (subcommand, expected) in [
        ("input", PromptKind::Input),
        ("textarea", PromptKind::Textarea),
    ] {
        let mut runtime = RuntimeProbe::default();
        let args = [OsStr::new(subcommand)];
        let status = ink::cli::run_from(&args, &mut runtime)
            .expect("compiled static tables should parse the prompt command");
        assert_eq!(status, std::process::ExitCode::SUCCESS);
        assert_eq!(runtime.prompts, [expected]);
        assert!(runtime.stdout.is_empty());
    }
}

#[test]
fn perf_002_startup_benchmark_uses_stable_sampling() {
    let mut invocations = 0;
    let median = ink::startup_bench::measure(|| {
        invocations += 1;
        Duration::from_millis(invocations)
    });
    assert_eq!(invocations, 120);
    assert_eq!(
        median,
        Duration::from_millis(70) + Duration::from_micros(500)
    );

    let temp = TempDir::new("startup-protocol");
    let fixture = temp.0.join("samples");
    fs::write(&fixture, "1000000\n".repeat(WARMUPS + SAMPLES))
        .expect("sample fixture should be written");
    let output = Command::new(env!("CARGO_BIN_EXE_startup-bench"))
        .env(SAMPLE_FIXTURE_ENV, fixture)
        .env_remove(ENFORCE_BUDGET_ENV)
        .output()
        .expect("startup benchmark should run");
    assert!(output.status.success());
    let report = String::from_utf8_lossy(&output.stdout);
    assert!(report.contains("ink --version median:"));
    assert!(report.contains("(20 warmups, 100 samples)"));
}

#[test]
fn perf_003_startup_stays_within_budget() {
    let temp = TempDir::new("startup-budget");
    let fixture = temp.0.join("samples");
    fs::write(&fixture, "21000000\n".repeat(WARMUPS + SAMPLES))
        .expect("sample fixture should be written");

    let ordinary = Command::new(env!("CARGO_BIN_EXE_startup-bench"))
        .env(SAMPLE_FIXTURE_ENV, &fixture)
        .env_remove(ENFORCE_BUDGET_ENV)
        .output()
        .expect("unenforced startup benchmark should run");
    assert!(ordinary.status.success());
    assert!(String::from_utf8_lossy(&ordinary.stdout).contains("median: 21.000 ms"));

    let enforced = Command::new(env!("CARGO_BIN_EXE_startup-bench"))
        .env(SAMPLE_FIXTURE_ENV, &fixture)
        .env(ENFORCE_BUDGET_ENV, "1")
        .output()
        .expect("enforced startup benchmark should run");
    assert_eq!(enforced.status.code(), Some(1));
    assert!(
        String::from_utf8_lossy(&enforced.stderr).contains("startup median exceeds 20.0 ms budget")
    );
}
